services:
  authservice:
    image: authservice
    build:
      context: .
      dockerfile: AuthService/Dockerfile

  accessoryservice:
    image: accessoryservice
    build:
      context: .
      dockerfile: AccessoryService/Dockerfile

  cartandwishlistservice:
    image: cartandwishlistservice
    build:
      context: .
      dockerfile: CartAndWishListService/Dockerfile

  orderservice:
    image: orderservice
    build:
      context: .
      dockerfile: OrderService/Dockerfile

  exchangeservice:
    image: exchangeservice
    build:
      context: .
      dockerfile: ExchangeService/Dockerfile

  chatservice:
    image: chatservice
    build:
      context: .
      dockerfile: ChatService/Dockerfile

  profileservice:
    image: profileservice
    build:
      context: .
      dockerfile: ProfileService/Dockerfile

  paymentservice:
    image: paymentservice
    build:
      context: .
      dockerfile: PaymentService/Dockerfile

  commonconfigservice:
    image: commonconfigservice
    build:
      context: .
      dockerfile: CommonConfigService/Dockerfile
  kong-database:
    image: postgres:13
    container_name: kong-database
    environment:
      POSTGRES_USER: kong
      POSTGRES_DB: kong
      POSTGRES_PASSWORD: kongpass
    ports:
      - "5432:5432"
    networks:
      - kong-net

  kong-migrations:
    image: kong/kong-gateway:3.10.0.0
    depends_on:
      - kong-database
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_PASSWORD: kongpass
      KONG_PASSWORD: test
    command: kong migrations bootstrap
    networks:
      - kong-net

  kong-gateway:
    image: kong/kong-gateway:3.10.0.0
    container_name: kong-gateway
    depends_on:
      - kong-database
      - kong-migrations
    environment:
      KONG_DATABASE: postgres
      KONG_PG_HOST: kong-database
      KONG_PG_USER: kong
      KONG_PG_PASSWORD: kongpass
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001
      KONG_ADMIN_GUI_URL: http://localhost:8002
    ports:
      - "8000:8000"
      - "8443:8443"
      - "8001:8001"
      - "8444:8444"
      - "8002:8002"
      - "8445:8445"
      - "8003:8003"
      - "8004:8004"
    networks:
      - kong-net
      
version: '3.8'

networks:
  kong-net:
    driver: bridge
